
### Install Libraries ###
library(shinythemes)
library(shiny)


### Read data ###

# File generated by the backend workload 

enron_df_sender_1 <- frequency_table_sender
enron_df_recipient_1 <- frequency_table_recipient
enron_df_overall_1 <- most_active_employee_df

enron_df_sender_2 <- status_sender_df
enron_df_recipient_2 <- status_recipient_df
enron_df_overall_2 <- status_overall_df

enron_df_annual_sender_3 <- enron_df_annual_sender_3
enron_df_annual_overall_3 <- enron_df_annual_overall_3
enron_df_monthly_sender_3 <- enron_df_monthly_sender_3
enron_df_monthly_overall_3 <- enron_df_monthly_overall_3

enron_wordcloud_corpus_1999_4_1 <- enron_wordcloud_corpus_1999_4_1
enron_wordcloud_corpus_2000_4_1 <- enron_wordcloud_corpus_2000_4_1
enron_wordcloud_corpus_2001_4_1 <- enron_wordcloud_corpus_2001_4_1
enron_wordcloud_corpus_2002_4_1 <- enron_wordcloud_corpus_2002_4_1
enron_wordcloud_corpus_all_years_4_1 <- enron_wordcloud_corpus_all_years_4_1
enron_df_barchart_1999_4_1 <- enron_df_barchart_1999_4_1
enron_df_barchart_2000_4_1 <- enron_df_barchart_2000_4_1
enron_df_barchart_2001_4_1 <- enron_df_barchart_2001_4_1
enron_df_barchart_2002_4_1 <- enron_df_barchart_2002_4_1
enron_df_barchart_all_years_4_1 <- enron_df_barchart_all_years_4_1

enron_words_comparison_top5_4_2 <- enron_words_comparison_top5_4_2
enron_words_comparison_top10_4_2 <- enron_words_comparison_top10_4_2
enron_words_comparison_top15_4_2 <- enron_words_comparison_top15_4_2



### UI Part ###

ui <- fluidPage(
  theme = shinytheme('flatly'),
  
  ##### Navbar Page #####
  navbarPage(
    'Enron E-Mails Activity',
    
    ### Navbar 1 ### 
    tabPanel('Activity per employee',
             
             # Main Title
             titlePanel(
               h2('Analysis of employee e-mail activity',
                  windowTitle = 'Activity per employee',
                  style={'background-color:AliceBlue;
                           margin-bottom: -30px;
                           margin-left: 15px;
                           margin-right: 15px;
                           padding-bottom: 25px;
                           padding-top: 15px;
                           padding-left: 15px;
                           padding-right: 15px;'}
               )
             ),
             
             # Subtitle
             titlePanel(
               h5('Who is Enron\'s most active employee?',
                  windowTitle = 'Activity per employee Question',
                  style={'background-color:AliceBlue;
                           margin-bottom: 30px;
                           margin-left: 15px;
                           margin-right: 15px;
                           padding-bottom: 25px;
                           padding-left: 15px;
                           padding-right: 15px;'}
               )
             ), 
             
             # Layout for user input and content display
             sidebarLayout(
               position = c("left", "right"),
               fluid = TRUE,
               
               sidebarPanel(
                 
                 # User Input - Number of employee selection
                 sliderInput('employee_number_1',
                             width = '80%',
                             label = 'Select a number of employees (top n):',
                             min = 1, 
                             value = 5, 
                             max = 15, 
                             step = 1
                 ),
                 
                 # User Input - DataFrame category selection
                 radioButtons('category_select_1', 'Select a category:',
                              choiceNames = list(
                                'Sender',
                                'Recipient',
                                'Overall (Sender + Recipient)'
                              ),
                              choiceValues = list('Sender', 'Recipient', 'Overall')
                 )
               ),
               
               # Display the content
               mainPanel(
                 tags$head(
                   tags$style(
                     HTML("#dashboard{margin-bottom:50px;}")
                   )
                 ),
                 tags$label(h3('Enron\'s most active employees')),
                 tags$div(),
                 verbatimTextOutput('print_selection_1'),
                 plotOutput(outputId = 'plot_1')
                 
               )
             ),
             
    ), 
    
    
    
    ### Navbar 2 ###
    tabPanel('Activity per status',
             
             # Main Title
             titlePanel(
               h2('Analysis of the relationship between status and e-mail activity',
                  windowTitle = 'Activity per status',
                  style={'background-color:AliceBlue;
                           margin-bottom: -30px;
                           margin-left: 15px;
                           margin-right: 15px;
                           padding-bottom: 25px;
                           padding-top: 15px;
                           padding-left: 15px;
                           padding-right: 15px;'}
               )
             ),
             
             # Subtitle
             titlePanel(
               h5('In which status are we most likely to be active, in terms of sending and receiving e-mail?',
                  windowTitle = 'Activity per status Question',
                  style={'background-color:AliceBlue;
                           margin-bottom: 30px;
                           margin-left: 15px;
                           margin-right: 15px;
                           padding-bottom: 25px;
                           padding-left: 15px;
                           padding-right: 15px;'}
               )
             ),   
             
             # Layout for user input and content display
             sidebarLayout(
               position = c("left", "right"),
               fluid = TRUE,
               sidebarPanel(
                 
                 # User Input - Type of Value selection
                 radioButtons('comparison_type_2', 'Select a comparison type:',
                              choiceNames = list(
                                'Total of E-mails',
                                'Median',
                                'Mean'
                              ),
                              choiceValues = list('TotalEmails', 'Median', 'Mean')
                 ),
                 
                 # User Input - DataFrame category selection
                 radioButtons('category_select_2', 'Select a category:',
                              choiceNames = list(
                                'Sender',
                                'Recipient',
                                'Overall (Sender + Recipient)'
                              ),
                              choiceValues = list('Sender', 'Recipient', 'Overall')
                 ),
               ),
               
               # Display the content
               mainPanel(
                 tags$head(
                   tags$style(
                     HTML("#dashboard{margin-bottom:50px;}")
                   )
                 ),
                 tags$label(h3('Status and e-mail activity')),
                 tags$div(),
                 verbatimTextOutput('print_selection_2'),
                 plotOutput(outputId = 'plot_2')
               )
             ),
    ),             
    
    
    ### Navbar 3 ###
    navbarMenu('Activity over time',
               tabPanel('Annual Activity',
                        
                        # Main Title
                        titlePanel(
                          h2('Analysis of annual e-mail activity',
                             windowTitle = 'Activity over time Annual',
                             style={'background-color:AliceBlue;
                             margin-bottom: -30px;
                             margin-left: 15px;
                             margin-right: 15px;
                             padding-bottom: 25px;
                             padding-top: 15px;
                             padding-left: 15px;
                             padding-right: 15px;'}
                          )
                        ),
                        
                        # Subtitle
                        titlePanel(
                          h5('In which year was e-mail activity highest?',
                             windowTitle = 'Activity over time Annual',
                             style={'background-color:AliceBlue;
                             margin-bottom: 30px;
                             margin-left: 15px;
                             margin-right: 15px;
                             padding-bottom: 25px;
                             padding-left: 15px;
                             padding-right: 15px;'}
                          )
                        ),
                        
                        # Layout for user input and content display
                        sidebarLayout(
                          position = c("left", "right"),
                          fluid = TRUE,
                          sidebarPanel(
                            
                            # User Input - DataFrame category selection
                            radioButtons('category_select_3_1', 'Select a category:',
                                         choiceNames = list(
                                           'Sender',
                                           'Overall'
                                         ),
                                         choiceValues = list('Sender', 'Overall')
                            ),
                            
                            # User Input - Date range selection
                            dateRangeInput(inputId = 'select_date_range_3_1', 
                                           label = 'Select a date range',
                                           start = '1998-01-01',
                                           end = '2003-01-01',
                                           min = '1998-01-01',
                                           max = '2003-01-01'
                            ),
                            
                            # User Input - Interval graph selection
                            sliderInput('range_month_3_1',
                                        width = '80%',
                                        label = 'Select X-Axis interval (Months):',
                                        min = 1, 
                                        value = 4, 
                                        max = 12,
                                        step = 1,
                                        ticks= FALSE
                            )
                          ),
                          
                          # Display the content
                          mainPanel(
                            tags$head(
                              tags$style(
                                HTML("#dashboard{margin-bottom:50px;}")
                              )
                            ),
                            tags$label(h3('E-mail activity over time - Annual')),
                            tags$div(),
                            verbatimTextOutput('print_selection_3_1'),
                            plotOutput(outputId = 'plot_3_1')
                          )
                        ),
                        
               ),
               
               tabPanel('Monthly Activity',
                        
                        # Main Title
                        titlePanel(
                          h2('Analysis of monthly e-mail activity',
                             windowTitle = 'Activity over time Monthly',
                             style={'background-color:AliceBlue;
                             margin-bottom: -30px;
                             margin-left: 15px;
                             margin-right: 15px;
                             padding-bottom: 25px;
                             padding-top: 15px;
                             padding-left: 15px;
                             padding-right: 15px;'}
                          )
                        ),
                        
                        # Subtitle
                        titlePanel(
                          h5('Is there a specific activity for each month of the year?',
                             windowTitle = 'Activity over time Monthly',
                             style={'background-color:AliceBlue;
                             margin-bottom: 30px;
                             margin-left: 15px;
                             margin-right: 15px;
                             padding-bottom: 25px;
                             padding-left: 15px;
                             padding-right: 15px;'}
                          )
                        ),
                        
                        # Layout for user input and content display
                        sidebarLayout(
                          position = c("left", "right"),
                          fluid = TRUE,
                          sidebarPanel(
                            
                            # User Input - DataFrame category selection
                            radioButtons('category_select_3_2', 
                                         'Select a category:',
                                         choiceNames = list(
                                           'Sender',
                                           'Overall'
                                         ),
                                         choiceValues = list('Sender', 'Overall')
                            ),
                            
                            # User Input - Year selection (multiple choice)
                            checkboxGroupInput('year_select_3_2',
                                               'Select one or more years:',
                                               c('1999' = '1999',
                                                 '2000' = '2000',
                                                 '2001' = '2001',
                                                 '2002' = '2002'
                                               ),
                                               selected = '2001'
                            )
                          ),
                          
                          # Display the content
                          mainPanel(
                            tags$head(
                              tags$style(
                                HTML("#dashboard{margin-bottom:50px;}")
                              )
                            ),
                            tags$label(h3('E-mail activity over time - Monthly')),
                            tags$div(),
                            verbatimTextOutput('print_selection_3_2'),
                            plotOutput(outputId = 'plot_3_2')
                          )
                        ),                        
                        
               ),
               
    ),
    
    ### Navbar 4 ###
    navbarMenu('Content Messages',
               tabPanel('General Overview',
                        
                        # Main Title
                        titlePanel(
                          h2('General overview of the content of the messages',
                             windowTitle = 'Content Messages General Overview',
                             style={'background-color:AliceBlue;
                             margin-bottom: -30px;
                             margin-left: 15px;
                             margin-right: 15px;
                             padding-bottom: 25px;
                             padding-top: 15px;
                             padding-left: 15px;
                             padding-right: 15px;'}
                          )
                        ),
                        
                        # Subtitle
                        titlePanel(
                          h5('What were the Enron employees talking about?',
                             windowTitle = 'Content Messages General Overview',
                             style={'background-color:AliceBlue;
                             margin-bottom: 30px;
                             margin-left: 15px;
                             margin-right: 15px;
                             padding-bottom: 25px;
                             padding-left: 15px;
                             padding-right: 15px;'}
                          )
                        ),
                        
                        # Layout for user input and content display
                        sidebarLayout(
                          position = c("left", "right"),
                          fluid = TRUE,
                          sidebarPanel(
                            
                            # User Input - Graph selection
                            radioButtons('chart_select_4_1', 'Select a chart type :',
                                         choiceNames = list(
                                           'Wordcloud',
                                           'Bar Chart'
                                         ),
                                         choiceValues = list('Wordcloud', 
                                                             'Bar Chart')
                            ),
                            
                            # User Input - Year selection (single choice)
                            radioButtons('year_select_4_1', 'Select a year:',
                                         choiceNames = list(
                                           '1999',
                                           '2000',
                                           '2001',
                                           '2002',
                                           'Entire Period'
                                         ),
                                         choiceValues = list('1999', 
                                                             '2000',
                                                             '2001',
                                                             '2002',
                                                             'Entire Period')
                            ),
                            
                            # User Input - Number of words to be displayed
                            sliderInput('words_number_select_4_1',
                                        width = '80%',
                                        label = 'Select the number of words to be displayed:',
                                        min = 1, 
                                        value = 100, 
                                        max = 150,
                                        step = 1,
                                        ticks= FALSE
                            )
                          ),
                          
                          # Display the content
                          mainPanel(
                            tags$head(
                              tags$style(
                                HTML("#dashboard{margin-bottom:50px;}")
                              )
                            ),
                            tags$label(h3('Content of the messages')),
                            tags$div(),
                            verbatimTextOutput('print_selection_4_1'),
                            plotOutput(outputId = 'plot_4_1')
                          )
                        ),
                        
               ),
               
               tabPanel('Year Comparison',
                        
                        # Main Title
                        titlePanel(
                          h2('Yearly comparison of message content',
                             windowTitle = 'Content Messages Year comparison',
                             style={'background-color:AliceBlue;
                             margin-bottom: -30px;
                             margin-left: 15px;
                             margin-right: 15px;
                             padding-bottom: 25px;
                             padding-top: 15px;
                             padding-left: 15px;
                             padding-right: 15px;'}
                          )
                        ),
                        
                        # Subtitle
                        titlePanel(
                          h5('What were the Enron employees talking about?',
                             windowTitle = 'Content Messages Bar Chart',
                             style={'background-color:AliceBlue;
                             margin-bottom: 30px;
                             margin-left: 15px;
                             margin-right: 15px;
                             padding-bottom: 25px;
                             padding-left: 15px;
                             padding-right: 15px;'}
                          )
                        ),
                        
                        # Layout for user input and content display
                        sidebarLayout(
                          position = c("left", "right"),
                          fluid = TRUE,
                          sidebarPanel(
                            
                            # User Input - Graph selection
                            radioButtons('chart_select_4_2', 'Select a chart type :',
                                         choiceNames = list(
                                           'Bar Chart',
                                           'Heat Map'
                                         ),
                                         choiceValues = list('Bar Chart', 
                                                             'Heat Map')
                            ),  
                            
                            # User Input - Number of words to be displayed
                            sliderInput('words_number_select_4_2',
                                        width = '80%',
                                        label = 'Select the number of words to be displayed:',
                                        min = 5, 
                                        value = 10, 
                                        max = 15,
                                        step = 5,
                                        ticks= FALSE
                            )
                            
                          ),
                          
                          # Display the content
                          mainPanel(
                            tags$head(
                              tags$style(
                                HTML("#dashboard{margin-bottom:50px;}")
                              )
                            ),
                            tags$label(h3('Message content for 2000, 2001 and 2002')),
                            tags$div(),
                            verbatimTextOutput('print_selection_4_2'),
                            plotOutput(outputId = 'plot_4_2')
                          )
                        ),                        
                        
               )
               
    ),
    
  )
)



### Server Part ###

server <- function(input, output) {
  ### Functions for the Tab 1 ###
  
  
  
  # Tab 1 - Function 1 #
  # User selection print function
  
  output$print_selection_1 <- renderText({
    
    paste('The', input$employee_number_1, 'most active employees in the', input$category_select_1, 'category, is/are:')
    
  })
  
  
  
  # Tab 1 - Function 2 #
  # Display the Bar Chart
  
  output$plot_1 <- renderPlot({
    
    # Import inputs into different variables
    employee_number_1 <- input$employee_number_1
    df_select_name_1 <- input$category_select_1
    
    # Import the right DataFrame according to the user's choice
    if (df_select_name_1 == 'Sender') {
      df_select_1 <- enron_df_sender_1
    } else if (df_select_name_1 == 'Recipient') {
      df_select_1 <- enron_df_recipient_1
    } else {
      df_select_1 <- enron_df_overall_1
    }
    
    # Select the first n lines according to the user's choice
    df_select_1 <- df_select_1 %>% top_n(employee_number_1)
    
    # Display the chart
    ggplot(df_select_1, aes(x=reorder(EmployeeName, Emails), Emails)) + 
      geom_bar(stat = 'identity', fill = '#054C70') +
      coord_flip() + 
      labs(x = 'Employee Names', y = 'Number of E-mails') +
      geom_text(
        aes(label = Emails), 
        size = 5,
        vjust = 0.5,
        hjust = 1.5, 
        color = 'white') +
      theme(axis.text = element_text(face='bold', 
                                     size=12))
    
  })
  
  
  
  
  
  
  ### Functions for the Tab 2 ###
  
  
  
  # Tab 2 - Function 1 #
  # User selection print function
  
  output$print_selection_2 <- renderText({
    
    paste('Here\'s a comparison of Status activity using the', input$comparison_type_2, 'for the', input$category_select_2, 'category:')
    
  })
  
  
  
  # Tab 2 - Function 2 #
  # Display the Bar Chart
  
  output$plot_2 <- renderPlot({
    
    # Import inputs into different variables
    df_select_name_2 <- input$category_select_2
    comparison_type_2 <- input$comparison_type_2
    
    # Import the right DataFrame according to the user's choice
    if (df_select_name_2 == 'Sender') {
      df_select_2 <- enron_df_sender_2
    } else if (df_select_name_2 == 'Recipient') {
      df_select_2 <- enron_df_recipient_2
    } else {
      df_select_2 <- enron_df_overall_2
      
    }
    
    # Display the chart
    ggplot(df_select_2, aes(x=reorder(Status, -!!sym(comparison_type_2)), !!sym(comparison_type_2))) +
      geom_bar(stat = 'identity', fill = '#054C70') +
      labs(x = 'Status', y = 'Number of E-mails') +
      geom_text(
        aes(label = !!sym(comparison_type_2)), 
        size = 3,
        vjust = 1.5,
        hjust = 0.5, 
        color = 'white') +
      theme(axis.text.x = element_text(angle = 30, 
                                       vjust = 1, 
                                       hjust=1,
                                       face='bold'))
    
  })
  
  
  
  
  
  
  ### Functions for the Tab 3.1 ###
  
  
  
  # Tab 3.1 - Function 1 #
  # User selection print function
  
  output$print_selection_3_1 <- renderText({
    
    paste('Here\'s the number of e-mails for the', input$category_select_3_1, 'category, for the period from', input$select_date_range_3_1[1],'to',input$select_date_range_3_1[2], ':')
    
  })
  
  
  
  # Tab 3.1 - Function 2 #
  # Display the Line Chart
  
  output$plot_3_1 <- renderPlot({
    
    # Import inputs into different variables
    date_start_3_1 <- input$select_date_range_3_1[1]
    date_end_3_1 <- input$select_date_range_3_1[2]
    df_select_name_3_1 <- input$category_select_3_1
    range_month_number_3_1 <- input$range_month_3_1
    
    
    # Import the right DataFrame according to the user's choice
    # Choose the appropriate scale for the y-axis
    if (df_select_name_3_1 == 'Sender') {
      df_select_3_1 <- enron_df_annual_sender_3
      breaks_3_1 <- seq(0,35000, 5000)
    } else {
      df_select_3_1 <- enron_df_annual_overall_3
      breaks_3_1 <- seq(0,400000, 30000)
    }
    
    # Choose the appropriate font size
    if (range_month_number_3_1 == 1) {
      size_font_3_1 <- 6
    } else if (range_month_number_3_1 == 2) {
      size_font_3_1 <- 8
    } else {
      size_font_3_1 <- 10
    }
    
    # Concatenate 2 strings to create the y-axis scale variable
    range_month_string_3_1 <- as.character(range_month_number_3_1)
    date_breaks_3_1 <- paste(range_month_string_3_1, 'month', sep=" ")
    
    # Select the appropriate dates according to the user's choice
    df_select_3_1 <- df_select_3_1[df_select_3_1$Date >= date_start_3_1 & df_select_3_1$Date <= date_end_3_1, ]
    
    # Display the chart
    ggplot(df_select_3_1, aes(x=Date, y=EmailNumber)) +
      geom_point(colour = '#054C70', size=1.5) +
      geom_line(colour = '#054C70', linewidth=0.6) +
      scale_x_date(date_breaks = date_breaks_3_1, date_labels = "%b %y") +
      scale_y_continuous(breaks=breaks_3_1) + 
      labs(y = 'Number of E-mails') +
      theme(axis.text.x=element_text(size = size_font_3_1,
                                     angle = 30,
                                     vjust = 1,
                                     hjust = 1,
                                     face='bold'),
            axis.text.y=element_text(size = 10,
                                     face='bold'))
  })
  
  
  
  
  
  
  ### Functions for the Tab 3.2 ###
  
  
  
  # Tab 3.2 - Function 1 #
  # User selection print function
  
  output$print_selection_3_2 <- renderText({
    
    # Import inputs into different variables
    df_select_name_3_2 <- input$category_select_3_2
    year_select_list_3_2 <- input$year_select_3_2
    
    # Print a different message depending on whether the user has made a choice or not
    if(length(input$year_select_3_2) == 0) {
      print('Choose at least one year.')
    } else{
      paste('Here is the number of e-mails per month, for the', df_select_name_3_2, 'category, for the year(s)', toString(year_select_list_3_2), ':')
    }
    
  })
  
  
  
  # Tab 3.2 - Function 2 #
  # Display the Multiple Line Chart
  
  output$plot_3_2 <- renderPlot({
    
    # Import inputs into different variables
    df_select_name_3_2 <- input$category_select_3_2
    year_select_list_3_2 <- input$year_select_3_2
    
    # Import the right DataFrame according to the user's choice
    if (df_select_name_3_2 == 'Sender') {
      df_select_3_2 <- enron_df_monthly_sender_3
    } else {
      df_select_3_2 <- enron_df_monthly_overall_3
    }
    
    # Import specific years according to user's choice
    df_select_3_2 <- df_select_3_2[df_select_3_2$Years %in% year_select_list_3_2, ]
    
    # Based on the number of years selected, define the scale of the y-axis
    breaks_3_2 <- as.double(quantile(c(0, max(
      df_select_3_2$EmailNumber))))
    breaks_3_2 <- round_any(breaks_3_2, 10, f = ceiling) 
    
    # Based on the number of years selected, define the different colors 
    year_select_list_length_3_2 <- n_distinct(df_select_3_2$Years)
    
    if (year_select_list_length_3_2 == '1') {
      scale_color_3_2 <- c('#054C70')
    } else if (year_select_list_length_3_2 == '2') {
      scale_color_3_2 <- c('#054C70', '#7B1E7A')
    } else if (year_select_list_length_3_2 == '3') {
      scale_color_3_2 <- c('#054C70', '#7B1E7A', '#97CC04')
    } else {
      scale_color_3_2 <- c('#054C70', '#7B1E7A', '#97CC04', '#EEB902') 
    }
    
    # Display the Chart
    ggplot(data = df_select_3_2, aes(x = MonthNumber, y = EmailNumber, group = factor(Years), colour=factor(Years))) + 
      geom_line() +
      geom_point() +
      scale_x_continuous(breaks = df_select_3_2$MonthNumber, labels = df_select_3_2$Date) +
      scale_y_continuous(breaks=breaks_3_2) +
      labs(y = 'Number of E-mails', x = '', color = 'Years') +
      scale_color_manual(values=scale_color_3_2) +
      theme(axis.text.x=element_text(size = 10,
                                     angle = 30,
                                     vjust = 1,
                                     hjust = 1),
            axis.text.y=element_text(size = 10,
                                     face='bold'))
    
  })
  
  
  
  
  
  
  ### Functions for the Tab 4.1 ###
  
  
  
  # Tab 4.1 - Function 1 #
  # Function to update the slider input for the number of words depending of the chart choose
  
  observeEvent(input$chart_select_4_1, {
    
    # Import inputs into different variables
    chart_select_name_4_1 <- input$chart_select_4_1
    
    # Update slider input values according to selected chart
    if (chart_select_name_4_1 == 'Wordcloud') {
      
      updateSliderInput(inputId = 'words_number_select_4_1',
                        value = 100,
                        max = 150)
    } else {
      
      updateSliderInput(inputId = 'words_number_select_4_1',
                        value = 5,
                        max = 15)
    } 
    
  }) 
  
  
  
  # Tab 4.1 - Function 2 #
  # User selection print function
  
  output$print_selection_4_1 <- renderText({
    
    # Import inputs into different variables
    chart_select_name_4_1 <- input$chart_select_4_1
    year_select_name_4_1 <- input$year_select_4_1
    words_number_display_select_4_1 <- input$words_number_select_4_1
    
    # Print the personalized message
    paste('Here are the', words_number_display_select_4_1,'most frequently used words for the year', year_select_name_4_1,'using a',chart_select_name_4_1,':')
    
  })
  
  
  
  # Tab 4.1 - Function 3 #
  # Display the chart
  
  output$plot_4_1 <- renderPlot({
    
    # Import inputs into different variables
    chart_select_name_4_1 <- input$chart_select_4_1
    year_select_name_4_1 <- input$year_select_4_1
    words_number_display_select_4_1 <- input$words_number_select_4_1
    
    # Depending on the user's choice, display the right graph with the right parameters
    # The right Corpus/DataFrame, year and number of words to display
    if (chart_select_name_4_1 == 'Wordcloud') {
      
      if (year_select_name_4_1 == 1999) {
        df_select_wordcloud__4_1 <- enron_wordcloud_corpus_1999_4_1
      } else if (year_select_name_4_1 == 2000) {
        df_select_wordcloud__4_1 <- enron_wordcloud_corpus_2000_4_1
      } else if (year_select_name_4_1 == 2001) {
        df_select_wordcloud__4_1 <- enron_wordcloud_corpus_2001_4_1
      } else if (year_select_name_4_1 == 2002) {
        df_select_wordcloud__4_1 <- enron_wordcloud_corpus_2002_4_1
      } else {
        df_select_wordcloud__4_1 <- enron_wordcloud_corpus_all_years_4_1
      }
      
      # Display the Wordclou
      set.seed(123456)
      wordcloud(df_select_wordcloud__4_1, 
                max.words = words_number_display_select_4_1, 
                colors = brewer.pal(8, 'Dark2'), 
                random.order=FALSE, rot.per=0)      
      
    } else {
      
      if (year_select_name_4_1 == 1999) {
        df_select_barchart__4_1 <- head(enron_df_barchart_1999_4_1, words_number_display_select_4_1)
      } else if (year_select_name_4_1 == 2000) {
        df_select_barchart__4_1 <- head(enron_df_barchart_2000_4_1, words_number_display_select_4_1)
      } else if (year_select_name_4_1 == 2001) {
        df_select_barchart__4_1 <- head(enron_df_barchart_2001_4_1, words_number_display_select_4_1)
      } else if (year_select_name_4_1 == 2002) {
        df_select_barchart__4_1 <- head(enron_df_barchart_2002_4_1, words_number_display_select_4_1)
      } else {
        df_select_barchart__4_1 <- head(enron_df_barchart_all_years_4_1, words_number_display_select_4_1)
      }
      
      # Display the Bar Chart
      ggplot(df_select_barchart__4_1, aes(x=reorder(Words, Frequency), Frequency)) + 
        geom_bar(stat = 'identity', fill = '#054C70') +
        coord_flip() + 
        labs(x = '', y = 'Frequency') +
        geom_text(
          aes(label = Frequency), 
          size = 4,
          vjust = 0.5,
          hjust = 1.5, 
          color = 'white') +
        theme(axis.text = element_text(size = 10,
                                       face='bold')) 
      
    }
    
  })
  
  
  
  
  
  
  ### Functions for the Tab 4.2 ###
  
  
  
  # Tab 4.2 - Function 1 #
  # User selection print function
  
  output$print_selection_4_2 <- renderText({
    
    # Import inputs into different variables
    chart_select_name_4_2 <- input$chart_select_4_2
    words_number_display_select_4_2 <- input$words_number_select_4_2
    
    # Print the personalized message
    paste('Here are the', words_number_display_select_4_2,'most frequently used words for the years 2000, 2001 and 2002, using a',chart_select_name_4_2,':')
    
  })
  
  
  
  # Tab 4.2 - Function 2 #
  # Display the chart
  
  output$plot_4_2 <- renderPlot({
    
    # Import inputs into different variables
    chart_select_name_4_2 <- input$chart_select_4_2
    words_number_display_select_4_2 <- input$words_number_select_4_2
    
    
    # Depending on the user's choice, display the right DataFrame
    if (words_number_display_select_4_2 == 5) {
      df_select_4_2 <- enron_words_comparison_top5_4_2
    } else if (words_number_display_select_4_2 == 10) {
      df_select_4_2 <- enron_words_comparison_top10_4_2
    } else {
      df_select_4_2 <- enron_words_comparison_top15_4_2
    }    
    
    # Depending on the user's choice, display the right graph with the right parameters
    if (chart_select_name_4_2 == 'Bar Chart') {
      
      breaks_4_2 <- seq(0, 7500, 1000)
      
      # Display the Bar Chart
      ggplot(df_select_4_2, aes(Words, Count, fill = Years)) +
        geom_bar(stat='identity', position = "dodge") + 
        ylab('Number of occurrences of the word') +
        theme(axis.text.x = element_text(size = 10,
                                         angle = 30, 
                                         vjust = 1, 
                                         hjust=1, 
                                         face='bold'),
              axis.text.y = element_text(size = 10, 
                                         face='bold')) +
        scale_y_continuous(breaks=breaks_4_2) +
        scale_fill_manual(values = c("#40B5AD","#054C70", '#4682B4')) 
      
    } else {
      
      # Display the Heat Map
      ggplot(df_select_4_2, aes(Years, Words, fill = Count)) + 
        geom_tile() +
        scale_fill_gradient(low = '#FAF9F6', high = '#00008B', 
                            labels = c('0', '1500', '3000', '4500', '7500')) +
        scale_colour_brewer("Diamond\nclarity") +
        xlab('') +
        ylab('') +
        guides(fill = guide_colourbar(title = 'Number of occurrences \nof the word')) +
        theme(axis.text.x = element_text(size = 14, face='bold'),
              axis.text.y = element_text(size = 10, face='bold'))
      
    }
    
  })
  
}



### Run the application ### 

shinyApp(ui = ui, server = server)
